:sparkles: (code-of-conduct) Content is there, maybe style to adjuste
webaquebec/webaquebec pull request #107
Opened 2022-05-14 15:23 UTC by florianfmmartin

2022-05-14 21:26 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +            <h1 id='english' css={marginBetweenVersions}>
Il ne peut y avoir qu'un h1 dans une page

2022-05-14 21:28 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +        maxWidth='var(--max-container-width)'
Réduire un peu le max width ici pour faciliter la lecture sur desktop

2022-05-14 21:38 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <h2>1. COMPORTEMENT ATTENDU</h2>
Ça ne serait pas un titre ici mais plutôt une liste ordonnée (1., 2., etc.). Les numéros font s'ajouter automatiquement.

```
<ol>
  <li>
    COMPORTEMENT ATTENDU
    <div>
      <p>Nous souhaitons que tous les participants...</p>
      <p>...</p>
    </div>
  </li>
  <li>
    COMPORTEMENT INACCEPTABLE
    <div>
      <p>...</p>
      <p>...</p>
    </div>
  </li>
  ...
</ol>
``` 

Importer **orderedListStyle** de global.js pour le style pour que ça soit uniforme avec les listes dans les autres pages.

```
<ol css={orderedListStyle}>
...
</ol>
```

2022-05-14 21:41 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +  ul {
importer le style [unorderedListStyle](https://github.com/webaquebec/webaquebec/blob/develop/src/styles/global.js#L377) deja défini dans global.js pour que ça soit uniforme partout sur le site.

2022-05-14 21:42 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <ul>
Même chose ici. Importer le style [unorderedListStyle](https://github.com/webaquebec/webaquebec/blob/develop/src/styles/global.js#L377) deja défini dans global.js pour que ça soit uniforme partout sur le site.
```
<ul css={unorderedListStyle}>
....
</ul>
```

2022-05-14 21:43 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <ul>
Même chose ici. Importer le style [unorderedListStyle](https://github.com/webaquebec/webaquebec/blob/develop/src/styles/global.js#L377) deja défini dans global.js pour que ça soit uniforme partout sur le site.
```
<ul css={unorderedListStyle}>
....
</ul>
```

2022-05-14 21:43 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <ul>
Même chose ici. Importer le style [unorderedListStyle](https://github.com/webaquebec/webaquebec/blob/develop/src/styles/global.js#L377) deja défini dans global.js pour que ça soit uniforme partout sur le site.
```
<ul css={unorderedListStyle}>
....
</ul>
```

2022-05-14 21:43 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <ul>
Même chose ici. Importer le style [unorderedListStyle](https://github.com/webaquebec/webaquebec/blob/develop/src/styles/global.js#L377) deja défini dans global.js pour que ça soit uniforme partout sur le site.
```
<ul css={unorderedListStyle}>
....
</ul>
```

2022-05-14 21:47 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +            <a href='https://confcodeofconduct.com'>confcodeofconduct.com</a>
Ajouter `target="_blank" rel="nnoopener noreferrer"`  à la suite de href, soit :

`<a href='https://confcodeofconduct.com' target="_blank" rel="nnoopener noreferrer">`

2022-05-14 21:47 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +            <a href='mailto:sos@webaquebec.org'>sos@webaquebec.org</a>
Ajouter target="_blank" rel="nnoopener noreferrer" à la suite de href, soit :

<a href='https://confcodeofconduct.com' target="_blank" rel="nnoopener noreferrer">

2022-05-14 21:48 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +            <a href='https://confcodeofconduct.com'>confcodeofconduct.com</a>
Ajouter `target="_blank" rel="nnoopener noreferrer"à à la suite de href, soit :

`<a href='https://confcodeofconduct.com' target="_blank" rel="nnoopener noreferrer">`

2022-05-14 21:54 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +      <a css={introStyle} href='#english'>
Bien pensé 👍

2022-05-14 21:58 UTC, Lornz- requested changes
Voir commentaires.
Quelques ajustements liés à la sémantique de la page et uniformiser les styles.

2022-05-15 15:38 UTC, florianfmmartin commented on src/pages/code-de-conduite.jsx
> +          <h2>1. COMPORTEMENT ATTENDU</h2>
Ici le `orderedListStyle` ne marchait pas du tout, ça fesait des trucs vraiment weird

2022-05-15 16:29 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +          <h2>1. COMPORTEMENT ATTENDU</h2>
@florianfmmartin Effectivement, il y a un issue avec le reset des numéros. Je vais regarder ça.

2022-05-15 16:31 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>COMPORTEMENT ATTENDU</h2>
Enlever le h2 et le sortir du Stack, comme ceci :

```
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:31 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>ASSISTANTE IMMÉDIATE</h2>
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:34 UTC, Lornz- requested changes

2022-05-15 16:34 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>COMPORTEMENT INACCEPTABLE</h2>
Enlever le h2 et le sortir du Stack, comme ceci par exemple :

```
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:34 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>EXPECTED BEHAVIOR</h2>
Enlever le h2 et le sortir du Stack, comme ceci par exemple :

```
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:34 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>UNACCEPTABLE BEHAVIOR</h2>
Enlever le h2 et le sortir du Stack, comme ceci par exemple :

```
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:34 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <h2>IMMEDIATE ASSISTANCE</h2>
Enlever le h2 et le sortir du Stack, comme ceci par exemple :

```
<li>
   COMPORTEMENT ATTENDU
   <Stack space=....>
```

2022-05-15 16:36 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <ul>
Ajouter `unorderedListStyle` ici

```
<ul css={unorderedListStyle}>
```

2022-05-15 16:36 UTC, Lornz- commented on src/pages/code-de-conduite.jsx
> +              <ul>
Ajouter `unorderedListStyle` ici

```
<ul css={unorderedListStyle}>
```

2022-05-16 05:17 UTC, Lornz- approved these changes

2022-05-16 05:17 UTC, merged