:sparkles: (about tabs) Create about tabs
webaquebec/webaquebec pull request #108
Opened 2022-05-18 02:19 UTC by KrystinaH

2022-10-17 20:33 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +  transition: all 0.2s ease-in-out;
Ne jamais utiliser transition all pour des questions de performance. Toujours cibler la ou les propriétés css sur laquelle la transition s'applique (ex. **transform**, **color**, **background-color**, etc.)

2022-10-17 20:37 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +        <PageTitle css={h1AltStyle}>à propos</PageTitle>
Supprimer le `<h1>` précédent et appliquer `h1` sur `PageTitle` au lieu de `h2`

2022-10-17 20:38 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +export const PageTitle = styled.h2`
Appliquer un h1 ici (https://github.com/webaquebec/webaquebec/pull/108/commits/dd6dc98df67c1c9172c49d19aeb88c19bf746407#r997488465)

2022-10-17 21:11 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +const AboutTabs = ({ title, activeTabId }) => {
Mettre à jour les styles avec le [nouveau brand](https://www.figma.com/file/B2LVaFg7KblyhdNymeWB8F/WAQ22-web---d%C3%A9veloppement?node-id=2476%3A8748&viewport=2449%2C2274%2C0.51).
Voir [styles](https://github.com/webaquebec/webaquebec/blob/develop/src/views/ProgramPageView/Hero/Hero.styles.js#L91-L167) des tabs de la Programmation.

2022-10-17 21:14 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +      pageUrl: 'a-propos/notre-equipe',
Enlever `a-propos` devant

2022-10-17 21:14 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +      pageUrl: 'a-propos/quebec-numerique',
Enlever `a-propos` devant

2022-10-17 21:15 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +                  href={tab.pageUrl}
C'est un lien interne donc utiliser `to={tab.pageUrl}` au lieu de `href={tab.pageUrl}`

2022-10-17 21:16 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +const AboutTabs = ({ title, activeTabId }) => {
Retirer `title`

2022-10-17 21:18 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.jsx
> +  title: PropTypes.string.isRequired,
Retirer props `title`

2022-10-17 21:23 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +export const AboutLink = styled.a`
Ce sont des liens internes. Utiliser `Link` de Gatsby au lieu d'un `<a>` 

```js
import { Link } from 'gatsby';

...

export const AboutLink = styled.Link`
...
```

2022-11-29 14:26 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +  margin-right: 30px;
Au lieu d'utiliser un `margin-right` ici, tu peux utiliser `gap` à la place sur la liste `<ul>` qui est maintenant bien supporté par les différents browsers.

Pour que les gutters soient uniformes partout, tu peux aussi utiliser la variable css global `--container-gutter` qui vaut 16px. Ainsi, avec le gap ça donnerait: 

```js
gap: calc(var(--container-gutter * 2) // 32px
```

2022-11-29 14:26 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +    margin-right: 0;
En utilisant `gap`, ça t'évite aussi de devoir enlever le `margin-right` ici sur le dernier élément.

2022-11-29 14:52 UTC, Lornz- requested changes
Quelques ajustements à apporter et appliquer les styles du nouveau brand ✨💅
Ne pas oublier également de se mettre à jour avec `master` [of puppets 🎸🤘]

2022-11-29 17:26 UTC, Lornz- commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +
Ajouter ici une marge négative à droite avec un padding à droite de la même taille pour éviter ça :

![Screen Shot 2022-11-29 at 11 20 21 AM](https://user-images.githubusercontent.com/901831/204599210-ac044d19-f582-4d75-af33-3a9682407759.png)

```css
  margin-right: calc(var(--container-gutter) * -1);
  padding-right: var(--container-gutter);
```

2023-01-06 01:12 UTC, KrystinaH commented on src/views/AboutPagesView/AboutTabs/AboutTabs.styles.js
> +  margin-right: 30px;
Ça marche pas en mobile et jtrouve pas ça 100% clair ahah

2023-01-06 01:27 UTC, merged