Feat/our team page
webaquebec/webaquebec pull request #125
Opened 2023-01-16 18:06 UTC by KrystinaH

2023-05-02 20:54 UTC, Lornz- commented on src/images/stickers/vectorStickerAquaStar.svg
À supprimer

2023-05-02 20:54 UTC, Lornz- commented on src/images/stickers/vectorStickerBomb.svg
À supprimer

2023-05-02 20:54 UTC, Lornz- commented on src/images/stickers/vectorStickerDesign.svg
À supprimer

2023-05-02 20:54 UTC, Lornz- commented on src/images/stickers/vectorStickerFlame.svg
À supprimer

2023-05-02 20:54 UTC, Lornz- commented on src/images/stickers/vectorStickerMouse.svg
À supprimer

2023-05-02 20:54 UTC, Lornz- commented on src/images/team/vectorBigGrid.svg
À supprimer

2023-05-02 20:55 UTC, Lornz- commented on src/images/team/vectorSmallGrid.svg
À supprimer

2023-05-02 20:55 UTC, Lornz- commented on src/images/test.png
À supprimer

2023-05-02 20:57 UTC, Lornz- commented on src/pages/a-propos/notre-equipe.jsx
> +import alexisRodrigue from '../../images/about/volunteers/alexis_rodrigue.jpg';
C'est beau. Il me restera à optimiser l'affichage des images avec Gatsby Image.

2023-05-02 21:12 UTC, Lornz- commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.jsx
> +                      galleryStyle
Comme _galleryStyle_ est passé en props pour chaque component **TeamMemberCard**, on peut considérer que c'est true en tout temps. Tu peux donc enlever la props et merger le style associé dans celui par défaut.

2023-05-02 21:13 UTC, Lornz- commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.jsx
> +                        galleryStyle
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:13 UTC, Lornz- commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.jsx
> +                galleryStyle
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:13 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.jsx
> +const TeamMemberCard = ({ member, galleryStyle }) => {
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:13 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.jsx
> +    <MemberCard $galleryStyle={galleryStyle}>
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:14 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.jsx
> +  galleryStyle: PropTypes.bool,
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:37 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.styles.js
> +  ${({ $galleryStyle }) => $galleryStyle && galleryStyleCard}
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

Tu peux donc enlever la validation ici et ajouter le style galleryStyleCard directement à la suite.

2023-05-02 21:37 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.styles.js
> +  ${({ $galleryStyle }) => $galleryStyle && galleryStyleInfos}
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

Tu peux donc enlever la validation ici et ajouter le style galleryStyleInfos directement à la suite.

2023-05-02 21:37 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.styles.js
> +  ${({ $galleryStyle }) => $galleryStyle && galleryStyleName}
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

Tu peux donc enlever la validation ici et ajouter le style galleryStyleName directement à la suite.

2023-05-02 21:39 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.styles.js
> +  ${({ $galleryStyle }) => $galleryStyle && galleryStyleJob}
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

Tu peux donc enlever la validation ici et ajouter le style galleryStyleJob directement à la suite.

2023-05-02 21:39 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.styles.js
> +  ${({ $galleryStyle }) => $galleryStyle && galleryStyleList}
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

Tu peux donc enlever la validation ici et ajouter le style galleryStyleList directement à la suite.

2023-05-02 21:44 UTC, Lornz- commented on src/images/placeholder.jpg
Existe en double

2023-05-02 21:51 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.jsx
> +  galleryStyle: false,
Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/125/files#r1183056654)

2023-05-02 21:59 UTC, Lornz- commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.styles.js
> +    :not(:last-child) {
💡 Astuce : Au lieu  de 
```css
:not(:last-child) {
   margin-right: var(--container-gutter);
}
```

tu peux simplement utiliser la propriété `gap` sur l'élément parent `<ul>` soit :
```css
gap: var(--container-gutter);
```

2023-05-02 22:06 UTC, Lornz- commented on src/views/OurTeamPageView/TeamMemberCard/TeamMemberCard.jsx
> +        <ContactList $galleryStyle={galleryStyle}>
On pourrait commenter `<ContactList>` pour l'instant en attendant de voir si on l'affiche ou pas définitivement.

2023-05-02 22:07 UTC, Lornz- requested changes
Voir commentaires

2023-05-02 23:52 UTC, KrystinaH commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.jsx
> +                      galleryStyle
C'était pour les cartes du CA, ya pleins de styles reliés à ça advenant le cas où ils se décident à m'en donner les infos un jour ahah

2023-05-02 23:56 UTC, KrystinaH commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.styles.js
> +    :not(:last-child) {
Ça ne fonctionne pas et je suis vraiment loin d'être familière avec les variables css...

2023-05-03 00:32 UTC, Lornz- commented on src/views/OurTeamPageView/TeamGallery/TeamGallery.styles.js
> +    :not(:last-child) {
Hmm je viens d'essayer pis ça fonctionne. le gap doit être [ici](https://github.com/webaquebec/webaquebec/blob/0ba1219c86b6911b946b35aeed8a65248fffc0b0/src/views/OurTeamPageView/TeamGallery/TeamGallery.styles.js#L49). La variable css n'est pas supposé changer de quoi.

2023-05-04 20:51 UTC, Lornz- approved these changes
💯

2023-05-04 20:56 UTC, merged