:art:  Add missing links to landing page
webaquebec/webaquebec pull request #24
Opened 2021-04-18 15:52 UTC by KrystinaH

2021-04-24 13:25 UTC, Lornz- commented on src/components/Footer/Footer.jsx
> +    { year: '2012', link: 'http://2012.webaquebec.org/' },
La même chose mais en **https**. Valider les liens avant mise en prod.

2021-04-24 13:28 UTC, Lornz- commented on src/components/Header/Header.jsx
> +    slug: '/blogue/on-va-se-dire-les-vraies-affaires',
Il manque le domaine du site archivé. Ça devrait être `https://archives.webaquebec.org` (À valider). On pointera vers la nouvelle page lorsque le blogue sera disponible.

2021-04-24 13:33 UTC, Lornz- requested changes
Voir comentaires

2021-04-26 16:08 UTC, KrystinaH commented on src/components/Footer/Footer.jsx
> +    { year: '2012', link: 'http://2012.webaquebec.org/' },
Bin à moins que les liens soient changés avant la mise en prod, il n'y a pas de https dans les urls des sites de 2012 à 2015.

2021-04-26 16:14 UTC, KrystinaH commented on src/components/Header/Header.jsx
> +    slug: '/blogue/on-va-se-dire-les-vraies-affaires',
Si on reste dans la même veine que les urls dans le footer, ça ne devrait pas plutôt être ceci pour l'archive de l'année dernière? https://2020.webaquebec.org/blogue/on-va-se-dire-les-vraies-affaires

2021-04-26 22:49 UTC, merged