Feature/boutons
webaquebec/webaquebec pull request #3
Opened 2021-02-21 21:19 UTC by KrystinaH

2021-02-27 13:58 UTC, Lornz- commented on src/components/Button/Button.styles.js
> +  font-size: ${rem(16)};
Il y a un `font-size` de trop

2021-02-27 14:01 UTC, Lornz- commented on src/components/Button/Button.styles.js
> +  )};
Il me semble que 14px en mobile, c'est vraiment petit. Je le laisserai à 16px en tout temps  pour le version small. Laisses le comme ça pour l'instant, on validera avec Amélie.

2021-02-27 14:06 UTC, Lornz- commented on src/components/Button/Button.styles.js
> +  )};
J'avais oublié qu'on pouvait mettre un array de valeurs pour la base. Vu qu'on varie entre une base à 16px sur mobile et 20px en desktop, j'ajouterais donc 16 en plus de 20 soit comme ceci :
```
  ${breakpointsRange(
     [{ prop: 'fontSize', sizes: [16, 24], bases: [16, 20] }],
     ...
   )};
```

2021-02-27 14:07 UTC, Lornz- commented on src/components/Button/Button.styles.js
> +  )};
Même chose ici pour la base.

2021-02-27 14:23 UTC, Lornz- commented on src/components/Button/Button.jsx
> +      $small={small}
Je ne pense pas t'avoir dit la différence entre écrire `prop` vs `$prop` avec styled-components. On ajoute un `$` pour toutes les props qui ne sont pas intrinsèques à un élément. Par exemple pour le Button, `type` et `disabled` sont des propriétés de l'élément HTML <button> et `as` qui est une propriété que styled-components ajoute en plus à l'élément).

2021-02-27 14:38 UTC, Lornz- requested changes
Rien de majeur. Juste quelques petits ajustements. Good job 😎

2021-02-28 13:43 UTC, KrystinaH commented on src/components/Button/Button.jsx
> +      $small={small}
Ok donc ça va si j'ai mit un $ parce que small c'est custom, right?

2021-02-28 16:27 UTC, Lornz- commented on src/components/Button/Button.jsx
> +      $small={small}
Yup

2021-03-02 21:10 UTC, Lornz- commented on src/components/Button/Button.styles.js
> +      { prop: 'fontSize', sizes: [16, 16], bases: [16, 20] },
J'avais oublié de te le mentionner mais tu peux utiliser la même fonction `breakpointsRange` pour plusieurs props en même temps.

Je ne l'ai vu qu'après, j'ai fait quelques ajustements au niveau de la taille de la font et du spacing pour que ça fit exactement au pixel prêt sur la maquette sur mobile et desktop. Tu peux y jeter un oeil et d'en inspirer ailleurs pour la suite.

Aussi pour le `line-height` avec `breakpointsRange`, ne pas oublier de préciser que c'est _unitless_ en tout temps,  comme ceci :
`{ prop: 'lineHeight', sizes: [19, 24], bases: [16, 20], unit: '' }`

2021-03-02 21:11 UTC, Lornz- approved these changes

2021-03-03 01:47 UTC, merged