Feat/blogue
webaquebec/webaquebec pull request #67
Opened 2021-06-02 01:04 UTC by KrystinaH

2021-06-06 12:15 UTC, Lornz- commented on src/styles/global.js
> +
Ne pas mettre les styles pour le blogue post dans global.js ici. Dans le cas où les styles s'appliquent un contexte en particulier, les définir dans un fichier **.styles.js** ou directement dans une page, une vue ou un composant. Dans ce cas ci pour le blog post, créer une nouvelle section dans **BlogPostView** genre **PostSection**, ajouter **PostSection.jsx** contenant un wrapper avec **content** en props qui sera le contenu du post qu'on mettra dans une div avec _dangerouslySetInnerHTML_ :
```js
  <div dangerouslySetInnerHTML={{ __html: content }} />
```
 puis créer un fichier **PostSection.styles.js** dans lequel tu viendras copier/coller les styles que t'as défini ici dans gobal.js.
 
 Ça pourrait changer. Tout dépend de la manière dont je récupérerais les données venant de Wordpress avec GraphQL.

2021-06-06 12:30 UTC, Lornz- commented on src/views/BlogPostView/HeroSection/HeroSection.jsx
> +        <Button outlined iconFirst renderIcon={<IconArrow css={backArrow} />}>
Mettre également le **Button** dans un **Center** Layout avec `var(--max-container-width)` comme `maxWidth`

2021-06-06 12:38 UTC, Lornz- commented on src/views/BlogPostView/HeroSection/HeroSection.jsx
> +    <div>
Petite spécificité de React, tu peux utiliser des fragments `<>` ici qui permet de grouper des éléments enfants sans y ajouter de noeud (`<div>`) supplémentaire. 
```js
<> 
   <TitleWrapper>
   ...
</>
```

2021-06-06 13:00 UTC, Lornz- requested changes
Voir commentaires

Également, utiliser des verbes d'actions dans la description de tes commits (add, integrate, implement, remove, delete, update, etc.). Ça permet de donner plus d'indice sur de quoi il s'agit en regardant l'historique de git.

2021-06-11 00:05 UTC, KrystinaH commented on src/views/BlogPostView/HeroSection/HeroSection.jsx
> +        <Button outlined iconFirst renderIcon={<IconArrow css={backArrow} />}>
Pourquoi?

2022-03-16 17:31 UTC, merged