Feat/about page
webaquebec/webaquebec pull request #82
Opened 2021-12-30 18:32 UTC by KrystinaH

2022-01-08 14:12 UTC, Lornz- commented on src/pages/a-propos.jsx
> +import photoSection4 from '../images/aboutSections/section4.jpg';
Privilégier plutôt des noms explicites et non arbitraires pour les photos ici afin qu'on puisse déterminer d'un coup d'oeil à quelle section les photos sont rattachées :
ex. photoSectionProgrammation, photoSectionCommunity, etc.

2022-01-08 14:27 UTC, Lornz- commented on src/pages/a-propos.jsx
> +      </VideoSectionWrapper>
Contrairement à la page faq, il y a quand même pas mal de logique dans cette page. Comme t'as commencé à le faire, Il serait mieux de découper davantage le code en intégrant les sections complètes dans les Views. Ça sera plus facile à maintenir dans le temps. Dans ce cas ci, prendre de `<AboutTitle>` à `<VideoWrapper>` et mettre dans une view **src/views/AboutPageView/Hero/Hero.jsx** et séparer les styles associés dans  **src/views/AboutPageView/Hero/Hero.styles.js**. Tu n'auras plus qu'à importer ta section dans la page, soit ici 
```jsx
<Center
   maxWidth='770px'
   gutters='var(--container-gutter)'
   withText
   intrinsic
 >
   <Hero />
...
```

2022-01-08 14:31 UTC, Lornz- commented on src/pages/a-propos.jsx
> +      </Container>
Idem ici. Déplacer tout le code dans **src/views/AboutPageView/AboutSection/AboutSection.jsx** et importer la view dans la page 
```jsx
...

<AboutSection />
...
```

2022-01-08 14:33 UTC, Lornz- commented on src/pages/a-propos.jsx
> +      </GallerySection>
Idem ici. Déplacer tout le code dans **src/views/AboutPageView/GallerySection/GallerySection.jsx** et les styles associés dans **src/views/AboutPageView/GallerySection/GallerySection.styles.js** puis  importer la view dans la page 
```jsx
...

<AboutSection />
...
```

2022-01-08 14:39 UTC, Lornz- commented on src/styles/global.js
> +  overflow-x: hidden;
Malheureusement faudra trouver une façon de faire ici. J'avais déjà mis un `overflow-x: hidden` mais ça cause un problème d'affichage de la modal des filtres dans programmation 😅. Enlèves le, je trouverai une façon d'arranger ça.

2022-01-08 14:55 UTC, Lornz- commented on src/components/Sticker/Sticker.jsx
> +export default Sticker;
Tous les Stickers ne sont pas forcément "animable". C'est pourquoi il est préférable de le faire à la carte en utilisant le component **LazyAnimation** selon les cas. Aussi, si ça donne plus de contrôle pour personnaliser l'animation en changeant les props de LazyAnimation directement. C'est très bien pensé, toutefois pour ces raisons,  je le laisserai comme c'était avant.

2022-01-08 14:57 UTC, Lornz- commented on src/components/Header/Menu/Menu.jsx
> +import CloseButton from '../../CloseButton';
Good move 😎

2022-01-08 15:21 UTC, Lornz- commented on src/views/AboutPageView/GallerySection/GallerySection.jsx
> +import { RemoveScroll } from 'react-remove-scroll';
Un peu overkill comme librairie 😜 Il y a moyen de le faire à mitaine sans passer par une librairie pour désactiver le scroll. De plus, ça réduira la taille du bundle final car chaque librairie ajoutée dans le projet en augmente la taille. Tu peux le laisser comme ça pour l'instant. On checkera ça un peu plus tard.

2022-01-08 16:07 UTC, Lornz- requested changes
Overall good job 💯🙌👏  

Les ajustements demandés sont principalement d'ordre structurel dans le code pour une meilleure maintenabilité et utilisabilité. 

Il me manquerait à te donner les exemples avec **gatsby-image** pour optimiser l'affichage des images de la gallery. Je donne ça ce samedi plus tard dans la journée.

Aussi régler le conflit de _src/components/Header/Header.jsx_ avec **develop**

2022-01-09 20:42 UTC, KrystinaH commented on src/pages/a-propos.jsx
> +      </GallerySection>
J'ai déplacer le "children" à l'intérieur du composant, mais la raison pour laquelle toutes les images et les textes étaient en paramètre, c'est dans l'éventualité où ça devient pilotable du CMS, c'est loadé dans la page et passé aux composants non?

2022-01-09 20:43 UTC, KrystinaH commented on src/styles/global.js
> +  overflow-x: hidden;
Ça fait déborder la page en mobile... j'ai essayer d'autres choses dans succès...

2022-01-09 20:45 UTC, KrystinaH commented on src/components/Sticker/Sticker.jsx
> +export default Sticker;
J'avais déjà créé le composant dans la keynote section qui n'a jamais été mergée et je trouve ça vraiment pratique, parce que ça évite beaucoup de copie du code. Si tu ne veux pas l'utiliser, tant pis, mais moi je ne le changerai pas ahah.

2022-01-10 00:34 UTC, Lornz- commented on src/styles/global.js
> +  overflow-x: hidden;
I know. Je vais trouver une autre façon parce que je n'ai pas le choix avec la modal des filtres.

2022-01-10 00:34 UTC, Lornz- commented on src/pages/a-propos.jsx
> +      </GallerySection>
Tu peux juste faire passer le data en props

2022-01-10 00:49 UTC, Lornz- commented on src/components/Sticker/Sticker.jsx
> +export default Sticker;
Dans ce cas, renomme le **StickerAnimated** svp pour bien faire la distinction.

2022-01-10 00:57 UTC, Lornz- requested changes
Voir commentaires 👀

2022-02-05 16:47 UTC, Lornz- approved these changes

2022-02-05 16:48 UTC, merged