Feat/page contact
webaquebec/webaquebec pull request #89
Opened 2022-02-02 19:25 UTC by florianfmmartin

2022-03-20 16:55 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +            <NosAdresses>
Utiliser l'anglais le plus possible SVP

2022-03-20 16:57 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +export const NosAdresses = styled.h2`
Utiliser l'anglais le plus possible SVP

2022-03-20 17:00 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +const Adresses = () => (
Utiliser les termes en anglais le plus possible SVP

2022-03-20 19:29 UTC, Lornz- commented on src/pages/contact.jsx
> +    <StyledSection faded>
Pour respecter la structure du DOM ici, ajouter `as='div'` comme props pour transformer le tag HTML par défaut `<section>` du component en `<div>`, ce qui donne :
```jsx
<StyledSection as='div' faded>
```

2022-03-20 19:43 UTC, Lornz- commented on src/pages/contact.jsx
> +      <ContactIntro css={introStyle}>
Je sais qu'à l'université, on nous apprend à limiter le nombre de ligne dans le code le plus possible surtout en backend, ce qui est vrai pour certains langages mais plus vraiment en javascript car le code est minifié au build time dans le bundle. Pour cette raison, on peut se permettre d'aérer un plus le code en développement pour des questions de lisibilité. Donc ici, pour chaque chaque block distinct, tu peux séparer un espace entre les deux, ce qui donne :
```jsx
<ContactTitle>nous joindre</ContactTitle>

<ContactIntro css={introStyle}>
...
```

En revanche, tu peux omettre un espace pour des blocks du même type par exemple si aurait deux `<ContactInfo>` qui se suivraient ou bien dans le cas d'une liste :
```html
<ul>
   <li>...</li>
   <li>...</li>
   <li>...</li>
</ul>
```

Le but est de visuellement séparer ce qui diffère et rapprocher ce qui est identique.

2022-03-20 19:46 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +StickerHeader.propTypes = {
Ajouter `.isRequired` ici pour chaque props car ils sont ici essentiels soit :
```jsx
sticker: PropTypes.string.isRequired
```

2022-03-20 19:49 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +const StickerHeader = ({ sticker, name }) => {
Renommer ici pour `StickerHeading` où `heading` par traduction correspond au titre d'un document ou d'un paragraphe contrairement à `header` qui est plus l'en-tête d'une page.

2022-03-20 19:50 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +StickerHeader.defaultProps = {
Retirer les `defaultProps` car les props seront requises

2022-03-20 19:53 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +              <AdressesSpan> adresses</AdressesSpan>
Bien mais ici t'aurais pu aussi juste utiliser un span html sans forcément créer un component avec styled-component. Dans les styles, ça

2022-03-20 20:01 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +                  itemScope
J'ai finalement opté pour un [schema](https://github.com/webaquebec/webaquebec/blob/develop/src/components/SEO/schemas.js) [JSON-LD](https://json-ld.org/) pour les données structurées dans le header de la page au lieu d'utiliser les microdata comme c'est le cas ici. C'est la manière recommandée par [Google](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data) et sera plus facile à mettre à jour ultérieurement. Tu peux laisser comme ça pour l'instant mais faudrait idéalement enlever chaque attribut ici pour éviter toute confusion.

2022-03-20 20:03 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +      <Sidebar contentMin='58%' sideWidth='322px' side='left' space='0'>
//

2022-03-20 20:05 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +  }
Le `margin-left` ici n'est pas nécessaire. Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/89/files#r830666293).

2022-03-20 20:13 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +  border-width: 3px;
utiliser le shortcut ici :
```css
border: 3px solid ${colors.bleu80}
```

2022-03-20 20:14 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +  )};
Pour éviter de devoir ajuster le `height` à chaque fois selon la largeur du device, comme le container est un block enfant d'un container parent de type **flexbox**, tu peux retirer le `height` ici et ajouter un `flex-grow: 1` à la place, ce qui fait en sorte qu'il prendra toute la hauteur disponible de la section. En faisant ça, t'auras juste à ajouter un `min-height` qui correspondra à la hauteur minimum du container sur mobile, soit :
```css
min-height: 213px
```

2022-03-20 20:53 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +  }
Le `padding-left` et `margin-left` ici ne sont plus nécessaires. Voir [commentaire](https://github.com/webaquebec/webaquebec/pull/89/files#r830666293).

2022-03-20 21:03 UTC, Lornz- commented on src/views/ContactPageView/Adresses/index.js
> +// eslint-disable-next-line no-restricted-exports
Regarde dans tes configs mais tu ne devrais avoir à désactiver cette règle de eslint.

2022-03-20 21:03 UTC, Lornz- commented on src/views/ContactPageView/Form/index.js
> +// eslint-disable-next-line no-restricted-exports
Regarde dans tes configs mais tu ne devrais avoir à désactiver cette règle de eslint.

2022-03-20 21:03 UTC, Lornz- commented on src/views/ContactPageView/Info/index.js
> +// eslint-disable-next-line no-restricted-exports
Regarde dans tes configs mais tu ne devrais avoir à désactiver cette règle de eslint.

2022-03-20 21:08 UTC, Lornz- commented on src/views/ContactPageView/Info/Info.jsx
> +            <Img
Je vais demander à l'équipe Design de nous donner ici la même photo originale de meilleur qualité et en couleur à laquelle on appliquera le filtre duotone avec **gatsby-image** et **gatsby-plugin-sharp** ainsi que le border radius en CSS. Je te reviendrais avec les détails au moment voulu.

2022-03-20 21:15 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +            <AdresseBlockContainer>
Ici tu peux remplacer le container par un layout `Stack` avec 30px de spacing ce qui ajoutera automatiquement un 30px entre chaque bloc d'adresse comme sur la maquette soit :
```jsx
<Stack space='30px'>
   <AdresseBlock>
   <AdresseBlock>
   ...
</Stack>
```

2022-03-20 21:18 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +export const AdresseBlockContainer = styled.div`
À retirer. Voir commentaires :
https://github.com/webaquebec/webaquebec/pull/89/files#r830666293
https://github.com/webaquebec/webaquebec/pull/89/files#r830674160

2022-03-20 21:19 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +`;
À retirer. Voir commentaires :
https://github.com/webaquebec/webaquebec/pull/89/files#r830666293
https://github.com/webaquebec/webaquebec/pull/89/files#r830674160

2022-03-20 21:19 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +`;
Voir [commenaire](https://github.com/webaquebec/webaquebec/pull/89/files#r830674160)

2022-03-20 21:23 UTC, Lornz- commented on src/views/ContactPageView/Adresses/Adresses.styles.js
> +export const SectionContainer = styled(StyledSection)`
Utiliser une section HTML classique ici soit :
```js
export const SectionContainer = styled.section` 
```

2022-03-20 21:24 UTC, Lornz- commented on src/views/ContactPageView/Form/Form.styles.js
> +export const SectionContainer = styled.div`
Pour respecter la structure du DOM ici, utiliser section comme élément au lieu d'une div soit :
```js
export const SectionContainer = styled.section`
```

2022-03-20 21:25 UTC, Lornz- commented on src/views/ContactPageView/Info/Info.styles.js
> +export const SectionContainer = styled.div`
Pour respecter la structure du DOM ici, utiliser section comme élément au lieu d'une div soit :
```js
export const SectionContainer = styled.section`
```

2022-03-20 21:36 UTC, Lornz- commented on src/views/ContactPageView/Info/Info.jsx
> +      <Sidebar contentMin='328px' sideWidth='50%' side='left' space='0'>
La props `side='left'` peut être retirée ici car c'est la valeur par défaut dans le layout **Sidebar**.

2022-03-20 21:49 UTC, Lornz- requested changes
Dans l'ensemble, beau travail @florianfmmartin  😎 

Les ajustements demandés sont principalement pour rester conforme avec les pratiques instaurées dans le projet ainsi que certaines bonnes pratiques en CSS et HTML de manière générale.

2022-03-22 17:51 UTC, florianfmmartin commented on src/views/ContactPageView/Adresses/Adresses.jsx
> +      <Sidebar contentMin='58%' sideWidth='322px' side='left' space='0'>
`contentMin='458px'` ne marche pas, ça cause la map à être caché lorsque la taille de la fenêtre est plus petite que 458px

Ça semble être pour ça que je l'avait fait à l'envers

2023-02-08 22:43 UTC, Lornz- approved these changes

2023-04-25 21:47 UTC, merged