Feat/page a propos/section quebec numerique
webaquebec/webaquebec pull request #91
Opened 2022-03-07 16:08 UTC by florianfmmartin

2022-05-18 04:46 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QNLogo.png';
utilisez la version SVG svp

2022-05-18 04:49 UTC, Lornz- commented on src/pages/a-propos/quebec-numerique.jsx
> +    'Synergie et partage sont l’essence de la mission de Québec numérique (QN). Plus qu’une simple organisation sans but lucratif, Québec numérique joue un rôle rassembleur auprès de l’ensemble des a
Ce texte ne devrait pas changer avec le temps. Ça restera du contenu statique donc mettre directement le texte dans un paragraphe.

2022-05-18 04:50 UTC, Lornz- commented on src/pages/a-propos/quebec-numerique.jsx
> +  const description = {
Idem ici. Ce texte ne devrait pas changer avec le temps. Ça restera du contenu statique donc mettre directement le texte dans un paragraphe.

2022-05-18 04:50 UTC, Lornz- commented on src/pages/a-propos/quebec-numerique.jsx
> +  const joinUs =
Idem ici. Ce texte ne devrait pas changer avec le temps. Ça restera du contenu statique donc mettre directement le texte dans un paragraphe dans la section concernée.

2022-05-18 04:52 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +            <Paragraph>{text}</Paragraph>
Ajouter le texte directement ici.

2022-05-18 04:53 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +            <Button small primary animated tag='href' to={link}>
Le contenu restera statique donc tu peux ajouter le lien directement ici plutôt que de passer en props.

2022-05-18 04:53 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/WhoWeAreSection/WhoWeAreSection.jsx
> +      <Paragraph>{part1}</Paragraph>
Le contenu restera statique donc tu peux ajouter le texte dans le paragraphe directement ici plutôt que de passer en props.

2022-05-18 04:54 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/WhoWeAreSection/WhoWeAreSection.jsx
> +      <Paragraph>{part2}</Paragraph>
idem ici. Le contenu restera statique donc tu peux ajouter le texte dans le paragraphe directement ici plutôt que de passer en props.

2022-05-18 05:02 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/ImagesSection/ImagesSection.jsx
> +const Image = styled.img`
Utilisez **gatsby-image** ici plutôt pour activer le lazy loading.

```
import GatsbyImage from 'Gatsby-image';

...

const Image = styled(GatsbyImage)`
   ...
`
```

2022-05-19 00:25 UTC, florianfmmartin commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QNLogo.png';
Y'a pas de version SVG dans le figma! Tu peux export en SVG mais cest juste une image sur un fond blanc

2022-05-21 19:03 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QNLogo.png';
@florianfmmartin Si check les options à l'import

2022-05-21 19:05 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QNLogo.png';
<img width="1457" alt="Screen Shot 2022-05-21 at 3 04 32 PM" src="https://user-images.githubusercontent.com/901831/169665920-66607fce-18b7-4da5-8671-3bde841cf7d6.png">

2022-05-21 19:07 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QNLogo.png';
@florianfmmartin Ah ok désolé je comprends. Ils ont mis une image dans le svp 🤦‍♂️

2022-05-21 19:31 UTC, Lornz- commented on src/views/AboutQuebecNumeriquePageView/JoinUsSection/JoinUsSection.jsx
> +import QNLogo from '../../../images/about/quebec-numerique/QuebecNumeriqueLogo.svg';
À l'avenir, utilises la même convention pour le naming que les autres logo
**logo-quebec-numerique.svg**

Tu peux laisser comme ça pour l'instant.

2022-05-21 19:38 UTC, Lornz- requested changes
Il reste à changer le logo de Québec Numérique pour la version SVG (je t'ai uploadé le fichier sur Slack) ainsi que quelques ajustements mineures et ça sera prêt pour mettre en prod bientôt 😎

2022-05-21 20:41 UTC, Lornz- commented on src/pages/a-propos/quebec-numerique.jsx
> +    'Synergie et partage sont l’essence de la mission de Québec numérique (QN). Plus qu’une simple organisation sans but lucratif, Québec numérique joue un rôle rassembleur auprès de l’ensemble des a
@florianfmmartin Je viens de checker dans le code pour réaliser que **IntroSection** est effectivement le même composant utilisé dans **AboutEventSection**.  T'as bien fait d'ignorer mon précédent commentaire. 😉

2023-02-09 12:34 UTC, Lornz- approved these changes

2023-02-09 12:51 UTC, merged