:sparkles: (partners grid) Update of the partners grid on the home page
webaquebec/webaquebec pull request #92
Opened 2022-03-20 21:33 UTC by KrystinaH

2022-03-21 23:24 UTC, Lornz- commented on src/components/PartnersGrids/LogoCard/LogoCard.styles.js
> +  }
plus nécessaire

2022-03-21 23:25 UTC, Lornz- commented on src/components/PartnersGrids/LogoCard/LogoCard.styles.js
> +    }
plus nécessaire

2022-03-21 23:27 UTC, Lornz- commented on src/components/PartnersGrids/PartnersGrids.jsx
> +import logoUbisoft from '../../images/logoPartners/premium/logo-ubisoft.png';
Est-ce le seul qu'on n'a pas la version svg ?

2022-03-21 23:29 UTC, Lornz- commented on src/components/PartnersGrids/PartnersGrids.jsx
> +PartnersGrid.propTypes = {};
Pas nécessaire ici vu qu'on ne passe pas de props à **PartnersGrid**

2022-03-21 23:49 UTC, Lornz- commented on src/images/logoPartners/associates/logo-novarium.svg
> +<?xml version="1.0" encoding="UTF-8"?>
As-tu le plugin [SVGO Compressor](https://www.sketch.com/extensions/plugins/svgo-compressor/?_ga=2.16149046.1208540631.1647905570-1281698397.1647905570) installé dans Sketch ? Ça permet de compresser et donc de diminuer la taille d'un svg. Comme on commence à en avoir pas mal, j'ai tendance à le faire pour limiter l'espace que ça prend sur le serveur. Tu peux laisser comme ça pour l'instant, on pourra le faire dans un prochain commit. Tu pourras l'appliquer pour les prochains.

2022-03-22 00:04 UTC, Lornz- commented on src/pages/index.jsx
> +import PartnersGrids from '../components/PartnersGrids';
J'ai fait exprès de le mettre dans une section pour que ça soit cohérent avec le reste de la structure de la page dans le DOM pour l'accessibilité. Tu peux le laisser comme ça si tu le souhaites mais je la remettrais avant mise en prod.

2022-03-22 00:29 UTC, Lornz- requested changes
Voir commentaires

2022-03-22 16:21 UTC, KrystinaH commented on src/images/logoPartners/associates/logo-novarium.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Ah sorry, je suis habituée de travailler dans des projets dont le compresseur est à même la compilation.

2022-03-23 01:22 UTC, merged